### ISSUE TITLE
Integrating Intercom into the UI

### ISSUE THREAD

**Issue by andrewMacmurray** [cast-fuse/action-for-children#28]
@ToriCAST @rachaeltownley @andrewsprinz @suninthesky

So @ivanmauricio and I started some research yesterday on [intercom](https://www.intercom.com/), it's an amazing service and the admin dashboard looks like the perfect thing for the `ACT` service.

However, the user facing (i.e. the parents using the service) side on intercom is built to appear as a widget on a website or app and not as an integral part of the user interface. We've had a dig around in the docs and there are very limited options on customising the UI.

There are a couple of different potential solutions to this:

1. We use the intercom API to grab data and render a custom UI. This is a very big technical overhead as we'd have to effectively re-make a lot of the features the intercom widget has out of the box.

2. We hack the styling of the intercom widget to make it look like it's part of the page.

3. We redesign the UI around the widget interface

Option 1 would be potentially more reliable long term but from an initial look at the docs I think this would be quite a **big** and potentially **risky technical challenge** (one that intercom recommends not doing https://developers.intercom.com/v2.0/docs/integration-guidelines). I'm not even sure we could pull it off in the time we've got (I know we can get data from the intercom api but I'm not sure how live chat would work - I don't think they have a public websocket we can connect to)

Option 2 would be less reliable long term (the styling might break later on) but I think this would be a much better solution for the prototype, we'd have all the existing features from the intercom widget but it would appear more part of the UI

Option 3 is the most reliable and easiest to implement but we'd sacrifice the UI design for this. Personally I think this isn't appropriate for the product as the chat is the main focus of the service and having it in the bottom right corner implies that's it's an "add on" rather than an integral part.

My personal recommendation would be a mixture of option 2 & 3, hacking the css to make the widget fit into our UI but adapt some of the intercom UI around our existing designs - i.e. it would look a little more "intercom like" but would look like a core part of our UI.

@ivanmauricio @suninthesky do you have any thoughts on this?

**Comment by andrewMacmurray** [comment]
I'm also going to chase up intercom on some other solutions to this problem (I asked them yesterday but they didn't get back to me)

**Comment by andrewsprinz** [comment]
Quick thoughts while we're waiting to hear if there are any other options.

Agree option 1. is a huge overhead and probably not viable.

As you say, option 2 isn't a long term solution, and hacking around it
could throw up a large number of gotchas.

As for option 3. We're not too precious about the UI of the pages at the
moment, they're really just indications of the flow, so we can shape the UI
around what's possible; one option may be to use a "custom launcher
<https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/customize-the-intercom-messenger-technical>",
so essentially the big "Talk now" button on the homepage launches the chat
widget.

One question, is there any way to autoload the widget when the page
instantiates?

Once we hear back from them and you've had more time to explore, we can
rework the user flows to fit.

A

**Comment by andrewMacmurray** [comment]
@andrewsprinz that all sounds good.

We're able to auto launch the widget on page load or when the user clicks on a button which is good:

![screen shot 2017-05-26 at 12 28 28](https://cloud.githubusercontent.com/assets/14013616/26492988/fa67ae60-420e-11e7-884a-d337fef7bb5a.png)

We can use the custom launcher too but this is a similar problem with the styling. I definitely think it would be good if we limit the number of css changes, we can keep an eye of this easier if they change things that break our custom styling.

**Comment by ivanmauricio** [comment]
Here's the conversation we have been having with the Intercom team

> Hey Ivan! I'm Bruno, one of the support engineers here at Intercom. 👋  We currently have our Messenger that allows you to get a live-chat method of communication on a webpage, are you trying to have a different way to communicate with your users, but still using our tools? Because if you can use our Messenger you won't need the API. 😉 
Regarding OAuth, this is only needed if you are building an integration where you are handling some other app's data yourself. In this case, you'll be just using the API or the Messenger to communicate right? If that's so, the normal API access is enough. 👍 

> Thanks Bruno, from what I understand we will only need API access.
As part of the service we are trying to implement, the live-chat would be the main feature of our site rather than just a widget. I was wondering how much the Messenger can be modified to fit in with our UI.
We would much rather use the Messenger as it has all the functionality we are after. However we are not sure how customisable this is.
Alternatively if we were to use the API, we are wondering if we can implement live chat in this way, with our own custom UI. Particularly we wanted to know if there's a websocket we can connect to or if we would be restrictred to the REST api?

> Gotcha, thank you for your reply. At the moment our Messenger can be customised the following way:
Customize the Intercom Messenger (basics) Written by Zara Burke
Customize the Intercom Messenger (technical) Written by Zara Burke
Anything outside of this would be a feature request but not something we can accommodate at the moment. If that's what you are looking for, then you may need to wrote your own front-end for the messaging part of the app. We currently don't have any websocket connection you can tap into, but you can definitely use our REST API and Webhooks to achieve this in real-time as well. 😉

**Comment by suninthesky** [comment]
@andrewMacmurray if using Intercom for the Fuse prototype I'd go with option 3, with a few custom landing pages (e.g. auto launch, 'Talk now', etc) and start sending users to it ASAP.

For something with greater customisation I'd probably use https://smooch.io/. Running their web messenger in embedded mode could be [worth a look](https://docs.smooch.io/guide/web-messenger/) as well.

**Comment by andrewMacmurray** [comment]
@suninthesky interesting, thanks for the link, that could be good if we do need more customisation

**Comment by andrewMacmurray** [comment]
decided to go with option 3. UI has been rejigged to fit around the intercom messenger as is and will augment functionality with the intercom api where possible
