### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by andrewMacmurray** [cast-fuse/action-for-children#38]
@rachaeltownley @andrewsprinz @ToriCAST 

We need to have some way of saving users so they can login on a different device, we can then boot the intercom widget with the user information so they have the same chat history.

Do you think we could have a signup / login form when the user clicks the "ask your question" button? We can keep them logged in via a session so this would only need to happen once / after the cookie expires

**Comment by andrewsprinz** [comment]
Ah. Yeah. Good point.

For now, we'd rather avoid forcing the user to register before talking, the
concept of signing up for something can put up quite a barrier to the sort
of casual conversations we want to encourage. It's a trade off, but better
people are comfortable starting a chat when they're tired / stressed
without thinking they have to create accounts etc, even if that means they
can't retrieve the chat in another device / once cookies expire.

We have looked at a few options whereby people can register after talking,
or they can be given a code which retrieves chat histories, but haven't
worked these through - maybe we can call chat tomorrow on Skype or
something? Got a catch up at 10am with Rachael so that may be a good time?

As a bit of an aside, in order to give us options such as the above in the
future, is it possible to persist what I assume are temporary Intercom
sessions in the app database? That way we can retrieve them if cookies
expire, and possibly associate users with them, or just special codes;
whatever route we go down for the user flow.

Not sure if that made any sense!

**Comment by andrewMacmurray** [comment]
@andrewsprinz catchup would be good. The problem with registering after talking is getting the data out of the messenger (it's a bit of a walled garden), once they enter their data in the messenger it's quite difficult to associate it with a user on our end.

I had a quick look at the session cookie and I don't think it will be any help saving it, it's different each time and it's visibly only tied to the app-id (I imagine this is for security)

**Comment by andrewMacmurray** [comment]
@andrewsprinz another big problem if we just let the cookie expire is that the family support worker wouldn't be able to contact the parent if they hadn't entered an email address or contact details, the messenger part of the app effectively gets cut off at this point.

**Comment by andrewsprinz** [comment]
Let's chat tomoz, sorry with the kid today so can't Skype.

We need to be looking at this as the start of a relationship; most of what
will come next will happen ad-hoc - they may exchange phone numbers,
emails, or they may want to come back to chat online. But we should try
really hard to not force people to register before using it - the
equivalent to a service user would be phoning up a crisis phone line and
having to give all of their personal details, or go through 'security'
before being able to talk - most would just hang up.

Totally unsubstantiated thought - could we:

1. When the user hits talk now, create a temp user in the app database,
then associate this user with the intercom session
2. Create a unique 'code' associated with this temp user in the app
database
3. Show this code to the user next to the chat window
4. When a user comes back, they can enter the code, which pulls out the
temp user from the app database, and loads the associated account from
Intercom?

Sorry I can't talk right now, speak tomorrow morning!

**Comment by andrewMacmurray** [comment]
closed with pr #41
